# Generated by Django 4.2.7 on 2023-11-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordsModel',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('eng_word', models.CharField(max_length=100)),
                ('eng_transcription', models.CharField(max_length=100)),
                ('ru_word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(choices=[('no', 'No'), ('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('adjective', 'Adjective'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], default=None, max_length=13)),
                ('level', models.CharField(choices=[('no', 'No'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=None, max_length=4)),
            ],
        ),
    ]
