# Generated by Django 4.2.7 on 2023-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsmodel',
            options={'verbose_name': 'Words', 'verbose_name_plural': 'Words'},
        ),
    ]
